### ISSUE TITLE
乐淘表单布局

### ISSUE THREAD

**Issue by zhengwei1949** [zhengwei1949/myblog#148]
```html
<div class="search">
     <input type="text">
     <input type="button" value="搜索">
</div>
```

```scss
.search{
    position: relative;
    padding:10px;
    input[type="text"]{
        height:30px;
        border:1px solid #069;
    }
    input[type="button"]{
        border:1px solid #069;
        background-color: #069;
        color: #fff;
        position: absolute;
        right:10px;
        top:10px;
        height: 30px;
        border-radius: 0;
    }
}
```
