### ISSUE TITLE
清除inline-block元素之间回车换行造成的的空白间隙

### ISSUE THREAD

**Issue by zhengwei1949** [zhengwei1949/myblog#32]
## 思路一
```css
.demo{
            letter-spacing: 0;
        }
        .demo a{
            display: inline-block;
            width:100px;
            text-decoration: none;
            border:1px solid green;
            font-size:20px;
            letter-spacing: 0;
        }
```
## 思路二
```css
.demo{
            font-size:0;
        }
        .demo a{
            display: inline-block;
            width:100px;
            text-decoration: none;
            border:1px solid green;
            font-size:20px;
        }
```
